### ISSUE TITLE
Kanban board setting up

### ISSUE THREAD

**Issue by Marcraphael12** [Marcraphael12/Catalog-of-my-things#14]
Our group project link: https://github.com/Marcraphael12/Catalog-of-my-things/projects/1
We are a team of 3 students working as follows:
Team member #1:  @hakichris 
Team member #2: @rica213 
Team member #3: @Marcraphael12

**Comment by Ismailco** [comment]
### Hi @Marcraphael12, @rica213, @hakichris, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ All the tasks included in the cards
✔️ Group tasks have a card on the board

## Required Changes ♻️
- [ ] Kindly make sure to divide the time (Xpt) between the students in the group evenly, The tasks assigned to @rica213 have 8pt while other students have 4pt 
- [ ] Kindly make sure to add more cards to your Kanban board, I would suggest creating the cards with one responsibility in mind, meaning you can create a card for every task or group two or three similar tasks together

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TadesseDev** [comment]
### Hi Team

### I'm Tadesse Alemayehu your reviewer for this Issue. :hand: 

Your project is complete! 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)



## Highlights
 - [x] Good job making the changes requested by the previous code reviewer. ✅

## Optional suggestions
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
